### ISSUE TITLE
Update to work with Python 3.11

### ISSUE THREAD

**Issue by Latseen** [HakaiInstitute/GlintMaskGenerator#39]
**Is your feature request related to a problem? Please describe.**
GlintMaskGenerator does not work with Python 3.11

**Describe the solution you'd like**
Update the project to be able to support Python 3.11

**Describe alternatives you've considered**
I have been able to run GlintMaskGenerator successfully with Python 3.11, just by changing 2 np.float and 1 np.int references to float and int respectively. 

Hello! 

Just wanted to post this here. At the current state, GlintMaskTools does not support Python 3.11

However, as mentioned above, I was able to successfully run GlintMaskTools with Python 3.11 after some fairly minor changes. 

Could this change be implemented? I can also give more information into what I changed within the current code if needed.

**Comment by tayden** [comment]
Hey @Latseen , absolutely this can and should be done. Did you want to open a pull request with your changes and I can try to get that done this week?

**Comment by Latseen** [comment]
Hi @tayden , just created a pull request. Something I did notice is that the code from the glint-mask-tools pypi package differs from the code on this repo. The changes I made worked for the pypi package, and seemingly worked for the code in this repo, but I am not entirely sure if it will work with the user interface here?

**Comment by tayden** [comment]
Thanks! I'll check that the CLI and GUI interfaces are all up to date and work and merge this in

**Comment by Latseen** [comment]
Sounds good! Would it also be possible to update the PyPi package as well?

**Comment by tayden** [comment]
Yep! It should build and publish it automatically with a new Release being published. Seems like it worked: https://pypi.org/project/glint-mask-tools/
